use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let source_path = manifest_dir.join("data/tag-definitions.tsv");
    println!("cargo:rerun-if-changed={}", source_path.display());

    let source = fs::read_to_string(&source_path).expect("read tag definition data");
    let mut seen = BTreeSet::new();
    let mut generated = String::from(
        "// @generated by metra-core/build.rs; edit data/tag-definitions.tsv instead.\n",
    );
    generated.push_str("const TAG_DEFINITIONS: &[TagDefinition] = &[\n");

    for (line_number, line) in source.lines().enumerate() {
        let line_number = line_number + 1;
        if line.trim().is_empty() || line.trim_start().starts_with('#') {
            continue;
        }
        let fields = line.split('\t').collect::<Vec<_>>();
        assert_eq!(
            fields.len(),
            4,
            "tag definition line {line_number} must have four tab-separated fields"
        );
        let namespace = fields[0];
        let id_text = fields[1];
        let name = fields[2];
        let description = fields[3];
        assert!(
            !namespace.is_empty() && !name.is_empty() && !description.is_empty(),
            "tag definition line {line_number} contains an empty field"
        );
        let id = if let Some(hex) = id_text.strip_prefix("0x") {
            u32::from_str_radix(&hex.replace('_', ""), 16)
        } else {
            id_text.parse::<u32>()
        }
        .unwrap_or_else(|_| panic!("invalid tag id on line {line_number}: {id_text}"));
        assert!(
            seen.insert((namespace, id)),
            "duplicate tag definition on line {line_number}: {namespace}:{id_text}"
        );
        generated.push_str(&format!(
            "    TagDefinition {{ namespace: {namespace:?}, id: {id}, name: {name:?}, description: {description:?} }},\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("build output directory"));
    fs::write(out_dir.join("tag_definitions.rs"), generated).expect("write generated tag data");
}
